### ISSUE TITLE
[BUG] - Ansible inventory persists across terraform runs

### ISSUE THREAD

**Issue by jdziat** [ansible/terraform-provider-ansible#73]
When attempting to recreate an ec2 instance i notice that the ansible inventory isn't cleaned up between runs. This results in old hosts being present in new runs.

```
 ls -lah /tmp

-rw-------  1 jdziat jdziat   23 Nov 10 14:33 .inventory-1296922160.ini
-rw-------  1 jdziat jdziat   23 Nov 19 19:03 .inventory-1628442196.ini
-rw-------  1 jdziat jdziat   23 Nov 19 19:07 .inventory-2325631511.ini
-rw-------  1 jdziat jdziat   23 Nov 19 19:01 .inventory-3344302912.ini
-rw-------  1 jdziat jdziat   23 Nov 19 19:05 .inventory-345304391.ini
-rw-------  1 jdziat jdziat   23 Nov 10 14:34 .inventory-3567346555.ini
-rw-------  1 jdziat jdziat   23 Nov 19 19:02 .inventory-771546304.ini

```
It would be nice if the ansible provider cleaned up after itself or used a new inventory per run.

Currently working around this by including the `local-exec` provisioner, however that feels kinda hacky and prone to errors if multiple ansible playbooks are being ran.

```terraform
resource "ansible_playbook" "this" {
  playbook                = "${path.module}/playbook.yml"
  name                    = var.hostname
  replayable              = true
  ignore_playbook_failure = var.ignore_playbook_failure
  extra_vars              = local.extra_vars
  provisioner "local-exec" {
    command = "rm -fr /tmp/.inventory-*"
  }
}
```

**Comment by jtognazzi** [comment]
shoudn't this be fixed by https://github.com/ansible/terraform-provider-ansible/pull/40

**Comment by jdziat** [comment]
> shoudn't this be fixed by #40

I'm using the latest version 1.1.0 and still encountering the issue. So I don't believe that fixes the core issue.

**Comment by jdziat** [comment]
@jtognazzi Looks like it grabs anything with the `inventory-` prefix:
https://github.com/ansible/terraform-provider-ansible/blob/main/provider/resource_playbook.go#L584-L607

**Comment by jtognazzi** [comment]
The mentionned PR was merged in July, the 1.1.0 release went out in May...
So it will be in the next release, but I have no idea when that would be..

**Comment by Krakazybik** [comment]
same on MacOS

```
~ cd /var/folders/dh/r5gppl3d7fq8vdth6xjl5pm40000gn/T/
➜  T ls -a | grep inven
.inventory-1153937578.ini
.inventory-1239342111.ini
.inventory-1423931517.ini
.inventory-1452005203.ini
.inventory-1519894362.ini
.inventory-1786143069.ini
.inventory-1992133005.ini
.inventory-2162192639.ini
.inventory-2177737766.ini
.inventory-2463021238.ini
.inventory-2531710080.ini
.inventory-2767891643.ini
.inventory-2892214384.ini
.inventory-3005179455.ini
.inventory-3006836554.ini
.inventory-3034582154.ini
.inventory-3137342217.ini
.inventory-3328691325.ini
.inventory-3519067486.ini
.inventory-3575489529.ini
.inventory-3625323482.ini
.inventory-3682229849.ini
.inventory-3705280358.ini
.inventory-3832967765.ini
.inventory-3840754045.ini
.inventory-386251770.ini
.inventory-3956018797.ini
.inventory-4125948038.ini
.inventory-4218558421.ini
.inventory-454199894.ini
.inventory-457005459.ini
.inventory-645204433.ini
.inventory-869093001.ini
```

**Comment by irishgordo** [comment]
thanks for the workaround @jdziat :smile: :+1:

**Comment by gravesm** [comment]
This should be fixed in version 1.2.0 of the provider.
